package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"
)

// seed-demo-output.json is the bridge between the three things that have to
// agree about one seeded world: the seeder that built it, `verify`, and a human
// (or a browser-driving agent) clicking through the UI. The dataset speaks in
// keys ("acme.de", "acme.w1", "M3/prepare"); the running system speaks in
// UUIDs. This file is the map between them, plus the credentials needed to log
// in as each demo user.
//
// It is DEMO material: it contains cleartext passwords, exactly as the dataset
// and docs/testing/seed-dataset.md do. It must never describe a real tenant.

// outputWarning is written into the file so nobody mistakes it for an artifact
// that may be kept around.
const outputWarning = "Demo credentials in cleartext. Generated by cmd/seed-demo from a local dataset; " +
	"never point this tool at anything but a throwaway database."

// seedOutput is the whole file.
type seedOutput struct {
	GeneratedAt string         `json:"generatedAt"`
	SpecPath    string         `json:"specPath"`
	APIBaseURL  string         `json:"apiBaseUrl"`
	AsOf        string         `json:"asOf"`
	Warning     string         `json:"warning"`
	Tenants     []tenantOutput `json:"tenants"`
}

// tenantOutput is one tenant's key → id map.
type tenantOutput struct {
	Key      string `json:"key"`
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
	TenantID string `json:"tenantId"`

	// Users is keyed by the dataset's user key.
	Users map[string]userOutput `json:"users"`
	// Entities, ObligationTypes and EntityObligations map a dataset key to the
	// created row's id.
	Entities          map[string]string `json:"entities"`
	ObligationTypes   map[string]string `json:"obligationTypes"`
	EntityObligations map[string]string `json:"entityObligations"`
	// DataTemplates maps a template type (VAT / CIT / WHT) to the tenant's
	// predefined template of that type.
	DataTemplates map[string]string `json:"dataTemplates"`
	// Workflows is keyed by the dataset's workflow key.
	Workflows map[string]workflowOutput `json:"workflows"`
	Documents []documentOutput          `json:"documents"`
	Counts    tenantCounts              `json:"counts"`
}

type userOutput struct {
	ID     string `json:"id"`
	Email  string `json:"email"`
	Name   string `json:"name"`
	Role   string `json:"role"`
	Status string `json:"status"`
	// ScopeEntity is the dataset key of the entity a scoped grant is limited
	// to, empty for a tenant-wide grant.
	ScopeEntity string `json:"scopeEntity,omitempty"`
	// Password is the demo password (see outputWarning).
	Password string `json:"password"`
}

type workflowOutput struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Category string `json:"category"`
	// Status is the workflow's status when the seeder finished with it.
	Status string `json:"status"`
	// Started reports whether task instances were generated.
	Started bool `json:"started"`
	// Templates maps a template key to its workflow_task id.
	Templates map[string]string `json:"templates"`
	// Instances maps "<periodCode>|<templateKey>" to the task instance's id.
	Instances map[string]string `json:"instances"`
}

type documentOutput struct {
	Workflow  string `json:"workflow"`
	Period    string `json:"period"`
	Task      string `json:"task"`
	FileName  string `json:"fileName"`
	ID        string `json:"id"`
	VersionID string `json:"versionId"`
	Versions  int    `json:"versions"`
}

// tenantCounts is the tally printed in the summary and stored for verify.
type tenantCounts struct {
	Users             int            `json:"users"`
	Entities          int            `json:"entities"`
	ObligationTypes   int            `json:"obligationTypes"`
	EntityObligations int            `json:"entityObligations"`
	Workflows         int            `json:"workflows"`
	WorkflowsStarted  int            `json:"workflowsStarted"`
	WorkflowTasks     int            `json:"workflowTasks"`
	Instances         int            `json:"instances"`
	InstancesByStatus map[string]int `json:"instancesByStatus"`
	Documents         int            `json:"documents"`
	DocumentVersions  int            `json:"documentVersions"`
	BackdatedRows     int            `json:"backdatedRows"`
}

// newTenantOutput starts an empty record with every map allocated, so the
// marshalled JSON never contains a null where a map is expected.
func newTenantOutput(key, slug, name, timezone string) *tenantOutput {
	return &tenantOutput{
		Key:               key,
		Slug:              slug,
		Name:              name,
		Timezone:          timezone,
		Users:             map[string]userOutput{},
		Entities:          map[string]string{},
		ObligationTypes:   map[string]string{},
		EntityObligations: map[string]string{},
		DataTemplates:     map[string]string{},
		Workflows:         map[string]workflowOutput{},
		Documents:         []documentOutput{},
		Counts:            tenantCounts{InstancesByStatus: map[string]int{}},
	}
}

// writeSeedOutput writes the file, creating the parent directory if needed. The
// JSON is indented and its maps marshal in sorted key order, so two runs of the
// seeder produce files that differ only in the ids and the timestamp.
func writeSeedOutput(path string, out seedOutput) error {
	if path == "" {
		return fmt.Errorf("no output path")
	}
	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", dir, err)
		}
	}
	encoded, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return fmt.Errorf("encode output: %w", err)
	}
	encoded = append(encoded, '\n')
	if err := os.WriteFile(path, encoded, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// formatInstant renders the generation time the way the API renders instants.
func formatInstant(t time.Time) string {
	return t.UTC().Format("2006-01-02T15:04:05.000Z")
}

// sortedStatuses returns the statuses of a tally in a stable order.
func sortedStatuses(byStatus map[string]int) []string {
	keys := make([]string, 0, len(byStatus))
	for status := range byStatus {
		keys = append(keys, status)
	}
	sort.Strings(keys)
	return keys
}
