package main

import (
	"context"
	"fmt"
	"net/http"

	"github.com/mohamadhallal/zentax-api/seed/demo/spec"
	"github.com/mohamadhallal/zentax-api/shared/apiclient"
)

// This file is the per-instance half of the seeder: given ONE workflow's spec
// and the ids its objects were created with, it produces the exact, ordered
// list of HTTP calls that turns the freshly generated (not_started, unassigned,
// empty) instances into the world the dataset describes — and then performs
// them as the right users.
//
// Planning and performing are separate on purpose: the plan is a pure function
// of (workflow spec, id map), so the mapping "this instance spec ⇒ these calls,
// in this order" is unit-testable against a fake transport, with no server and
// no database.
//
// THE ORDER IS THE CONTRACT ($schemaNotes.workflows.putOrder). Per workflow:
//
//  1. exactly one PUT per listed instance, carrying status + assignee + notes +
//     taxData + taxDataStatus together;
//  2. every document upload (a pending_approval or approved instance freezes
//     its documents with a 409, so uploads must precede the submits);
//  3. every submit-for-approval;
//  4. every approve.
//
// Within each phase the dataset's own order is kept, so two runs of the seeder
// issue byte-identical requests in an identical sequence.

// Action kinds. A JSON action is one request with an optional JSON body; an
// upload action is a multipart POST, optionally followed by a second multipart
// POST that adds version 2 of the same document.
const (
	actionJSON   = "json"
	actionUpload = "upload"
)

// action is one planned HTTP call.
type action struct {
	// Kind is actionJSON or actionUpload.
	Kind string
	// Actor is the spec user key whose session performs the call — never a
	// session pointer, so a plan can be compared without a live login.
	Actor string
	// Method and Path are the request line (Path is absolute on the API, e.g.
	// "/task-instances/<uuid>").
	Method string
	Path   string
	// Body is the JSON body, or nil for none.
	Body any

	// Fields are the multipart text fields (upload actions only).
	Fields map[string]string
	// FileName is the uploaded file's name; FileKind is the dataset's
	// pdf|text|csv, which decides the generated bytes and the MIME type.
	FileName string
	FileKind string
	// NewVersion asks for a second POST to /documents/{id}/versions after the
	// upload succeeds.
	NewVersion bool

	// Period and Task are the dataset coordinates of the instance the action
	// acts on, kept so a result can be recorded against them without parsing
	// Ref back apart.
	Period string
	Task   string

	// Ref locates the action in the dataset ("acme.w1 M1/prepare") and Label
	// says what it does ("PUT status=completed"). Every error names both, so a
	// 400 from a validation rule is debuggable without re-reading this file.
	Ref   string
	Label string
}

func (a action) String() string {
	return fmt.Sprintf("%s: %s as %s", a.Ref, a.Label, a.Actor)
}

// fail wraps err with everything needed to locate the failure.
func (a action) fail(err error) error {
	return fmt.Errorf("%s: %s %s: %w", a, a.Method, a.Path, err)
}

// workflowRefs are the server ids the planner substitutes for dataset keys.
type workflowRefs struct {
	// WorkflowID is the created workflow's id.
	WorkflowID string
	// InstanceIDs maps instanceKey(period, taskKey) to the generated task
	// instance's id.
	InstanceIDs map[string]string
	// UserIDs maps a spec user key to that member's id.
	UserIDs map[string]string
}

// instanceKey is the (period, task-template) handle instances and documents are
// addressed by, in the dataset and in the seeder's own maps.
func instanceKey(period, task string) string { return period + "|" + task }

// planWorkflowActions builds the ordered call list for one workflow. It returns
// an error — never a partial plan — when a dataset key has no id, because that
// means the workflow was not started (or the caller's map is wrong) and half a
// plan would leave the demo in a state nothing describes.
func planWorkflowActions(w spec.Workflow, refs workflowRefs) ([]action, error) {
	if refs.WorkflowID == "" {
		return nil, fmt.Errorf("workflow %s: no workflow id", w.Key)
	}
	actions := make([]action, 0, len(w.Instances)*2+len(w.Documents))

	// 1. the single PUT per listed instance.
	for _, inst := range w.Instances {
		a, err := planInstancePut(w, inst, refs)
		if err != nil {
			return nil, err
		}
		actions = append(actions, a)
	}

	// 2. documents, while every instance is still unfrozen.
	for _, doc := range w.Documents {
		a, err := planDocumentUpload(w, doc, refs)
		if err != nil {
			return nil, err
		}
		actions = append(actions, a)
	}

	// 3. submits (via=submit stops here; via=approve continues to phase 4).
	for _, inst := range w.Instances {
		if inst.Via != spec.ViaSubmit && inst.Via != spec.ViaApprove {
			continue
		}
		a, err := planInstanceAction(w, inst, refs, "/submit-for-approval", w.Writer, "POST submit-for-approval")
		if err != nil {
			return nil, err
		}
		actions = append(actions, a)
	}

	// 4. approvals, by the approver — a different user with task:approve (SoD).
	for _, inst := range w.Instances {
		if inst.Via != spec.ViaApprove {
			continue
		}
		a, err := planInstanceAction(w, inst, refs, "/approve", w.Approver, "POST approve")
		if err != nil {
			return nil, err
		}
		actions = append(actions, a)
	}

	return actions, nil
}

// updateTaskInstanceBody mirrors dto.UpdateTaskInstanceBody. Only the fields
// the dataset sets are present: the API rejects an unknown body field with a
// 400, and an omitted one keeps the instance's current value (dueDate and
// dataTemplateId are inherited from the generator and the task template).
type updateTaskInstanceBody struct {
	Status        string         `json:"status"`
	AssigneeID    *string        `json:"assigneeId,omitempty"`
	Notes         *string        `json:"notes,omitempty"`
	TaxData       map[string]any `json:"taxData,omitempty"`
	TaxDataStatus string         `json:"taxDataStatus,omitempty"`
}

// planInstancePut builds the one PUT that carries every deviation of an
// instance. For via=submit / via=approve the PUT sets in_progress: the approval
// statuses are reachable only through the dedicated actions, and the PUT has to
// land before the instance freezes.
func planInstancePut(w spec.Workflow, inst spec.Instance, refs workflowRefs) (action, error) {
	ref := instanceRef(w, inst)

	instanceID, ok := refs.InstanceIDs[instanceKey(inst.Period, inst.Task)]
	if !ok || instanceID == "" {
		return action{}, fmt.Errorf("%s: no task instance was generated for this (period, task) — "+
			"the workflow was not started, or its periods/templates do not match the dataset", ref)
	}

	status := inst.Status
	if inst.Via == spec.ViaSubmit || inst.Via == spec.ViaApprove {
		status = "in_progress"
	}

	body := updateTaskInstanceBody{Status: status}
	if inst.Assignee != "" {
		assigneeID, ok := refs.UserIDs[inst.Assignee]
		if !ok || assigneeID == "" {
			return action{}, fmt.Errorf("%s: assignee %q has no member id (it must be an invited, "+
				"accepted, still-active member of this tenant)", ref, inst.Assignee)
		}
		body.AssigneeID = &assigneeID
	}
	if inst.Notes != "" {
		notes := inst.Notes
		body.Notes = &notes
	}
	if len(inst.TaxData) > 0 {
		body.TaxData = inst.TaxData
		body.TaxDataStatus = inst.TaxDataStatus
	}

	return action{
		Kind:   actionJSON,
		Actor:  w.Writer,
		Method: http.MethodPut,
		Path:   "/task-instances/" + instanceID,
		Body:   body,
		Period: inst.Period,
		Task:   inst.Task,
		Ref:    ref,
		Label:  "PUT status=" + status,
	}, nil
}

// planInstanceAction builds a bodyless POST on one instance (submit / approve).
func planInstanceAction(
	w spec.Workflow, inst spec.Instance, refs workflowRefs, suffix, actor, label string,
) (action, error) {
	ref := instanceRef(w, inst)
	instanceID, ok := refs.InstanceIDs[instanceKey(inst.Period, inst.Task)]
	if !ok || instanceID == "" {
		return action{}, fmt.Errorf("%s: no task instance for this (period, task)", ref)
	}
	if actor == "" {
		return action{}, fmt.Errorf("%s: %s needs an actor, but the workflow declares none", ref, label)
	}
	return action{
		Kind:   actionJSON,
		Actor:  actor,
		Method: http.MethodPost,
		Path:   "/task-instances/" + instanceID + suffix,
		Period: inst.Period,
		Task:   inst.Task,
		Ref:    ref,
		Label:  label,
	}, nil
}

// planDocumentUpload builds the multipart POST that attaches one document to a
// task instance, uploaded by the workflow's writer (document:write).
func planDocumentUpload(w spec.Workflow, doc spec.Document, refs workflowRefs) (action, error) {
	ref := fmt.Sprintf("%s %s/%s document %q", w.Key, doc.Period, doc.Task, doc.FileName)

	instanceID, ok := refs.InstanceIDs[instanceKey(doc.Period, doc.Task)]
	if !ok || instanceID == "" {
		return action{}, fmt.Errorf("%s: no task instance for this (period, task)", ref)
	}

	fields := map[string]string{
		"documentType":   doc.DocumentType,
		"taskInstanceId": instanceID,
	}
	if doc.Category != "" {
		fields["category"] = doc.Category
	}
	if doc.Label != "" {
		fields["label"] = doc.Label
	}
	if doc.Notes != nil && *doc.Notes != "" {
		fields["notes"] = *doc.Notes
	}

	label := "POST document " + doc.DocumentType
	if doc.NewVersion {
		label += " (+1 version)"
	}
	return action{
		Kind:       actionUpload,
		Actor:      w.Writer,
		Method:     http.MethodPost,
		Path:       "/workflows/" + refs.WorkflowID + "/documents",
		Fields:     fields,
		FileName:   doc.FileName,
		FileKind:   doc.Kind,
		NewVersion: doc.NewVersion,
		Period:     doc.Period,
		Task:       doc.Task,
		Ref:        ref,
		Label:      label,
	}, nil
}

func instanceRef(w spec.Workflow, inst spec.Instance) string {
	return fmt.Sprintf("%s %s/%s", w.Key, inst.Period, inst.Task)
}

// actionResult is what performing one action produced. DocumentID / VersionID
// are set for uploads only.
type actionResult struct {
	Action     action
	DocumentID string
	VersionID  string
}

// documentView is the subset of the upload response the seeder records.
type documentView struct {
	ID        string `json:"id"`
	VersionID string `json:"versionId"`
	Version   int    `json:"version"`
}

// executeActions performs a plan in order, each call on its actor's session.
// It stops at the first failure and returns an error naming the dataset object,
// the action and the request, with the API's own message attached.
func executeActions(
	ctx context.Context, sessions map[string]*apiclient.Session, actions []action,
) ([]actionResult, error) {
	results := make([]actionResult, 0, len(actions))
	for _, a := range actions {
		session, ok := sessions[a.Actor]
		if !ok || session == nil {
			return results, fmt.Errorf("%s: no logged-in session for %q", a, a.Actor)
		}
		result, err := executeAction(ctx, session, a)
		if err != nil {
			return results, err
		}
		results = append(results, result)
	}
	return results, nil
}

// executeAction performs one action on one session.
func executeAction(ctx context.Context, session *apiclient.Session, a action) (actionResult, error) {
	result := actionResult{Action: a}

	if a.Kind == actionJSON {
		if err := session.Do(ctx, a.Method, a.Path, a.Body, nil); err != nil {
			return result, a.fail(err)
		}
		return result, nil
	}

	content, err := documentBody(a.FileKind, a.FileName, a.Fields["label"], 1)
	if err != nil {
		return result, a.fail(err)
	}
	var created documentView
	if err := session.PostMultipart(ctx, a.Path, a.Fields, "file", a.FileName, content, &created); err != nil {
		return result, a.fail(err)
	}
	result.DocumentID = created.ID
	result.VersionID = created.VersionID

	if !a.NewVersion {
		return result, nil
	}
	if created.ID == "" {
		return result, a.fail(fmt.Errorf("upload returned no document id, so version 2 cannot be added"))
	}
	content2, err := documentBody(a.FileKind, a.FileName, a.Fields["label"], 2)
	if err != nil {
		return result, a.fail(err)
	}
	versionFields := map[string]string{}
	if label := a.Fields["label"]; label != "" {
		versionFields["label"] = label
	}
	var updated documentView
	versionPath := "/documents/" + created.ID + "/versions"
	if err := session.PostMultipart(ctx, versionPath, versionFields, "file", a.FileName, content2, &updated); err != nil {
		return result, fmt.Errorf("%s: POST %s: %w", a, versionPath, err)
	}
	result.VersionID = updated.VersionID
	return result, nil
}
