package main

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
)

// Document bodies are generated in memory, never read from disk: the demo has
// to be reproducible on a laptop and in a container, and a fixture directory
// would be one more thing to keep in step with the dataset.
//
// Two rules constrain what may be generated (modules/documents/domain/mime.go):
// the declared content type must be on the upload allowlist, and the server
// sniffs the first 512 bytes — a CONCRETE sniff (application/pdf) must equal
// the declared type, while a generic sniff (text/plain, octet-stream) accepts
// whatever was declared. So the pdf kind must really begin with "%PDF-", and
// the text / csv kinds must be plain text.
//
// Everything here is a pure function of (kind, file name, label, version), so
// the same run produces the same bytes — and therefore the same sha256 in the
// documents table — every time.

// documentBody renders the bytes for one uploaded file. version is 1 for the
// initial upload and 2 for the extra version the dataset's newVersion asks for;
// it appears in the content so the two versions differ (a document version is
// content-addressed by sha256).
func documentBody(kind, fileName, label string, version int) ([]byte, error) {
	if version < 1 {
		version = 1
	}
	title := label
	if title == "" {
		title = fileName
	}
	switch kind {
	case "pdf":
		return pdfDocument(title, fileName, version), nil
	case "text":
		return []byte(textDocument(title, fileName, version)), nil
	case "csv":
		return []byte(csvDocument(title, fileName, version)), nil
	default:
		return nil, fmt.Errorf("unknown document kind %q (want pdf, text or csv)", kind)
	}
}

// documentLines is the human content every kind carries, in the same order.
func documentLines(title, fileName string, version int) []string {
	return []string{
		"ZenTax demo document",
		"Title: " + title,
		"File: " + fileName,
		"Version: " + strconv.Itoa(version),
		"Generated by cmd/seed-demo from seed/demo/dataset.json.",
		"Sample content only - not a real filing.",
	}
}

func textDocument(title, fileName string, version int) string {
	return strings.Join(documentLines(title, fileName, version), "\n") + "\n"
}

func csvDocument(title, fileName string, version int) string {
	var b strings.Builder
	b.WriteString("field,value\n")
	for _, line := range documentLines(title, fileName, version) {
		key, value, found := strings.Cut(line, ": ")
		if !found {
			key, value = "note", line
		}
		b.WriteString(csvField(key) + "," + csvField(value) + "\n")
	}
	return b.String()
}

func csvField(v string) string {
	if !strings.ContainsAny(v, `",`+"\n") {
		return v
	}
	return `"` + strings.ReplaceAll(v, `"`, `""`) + `"`
}

// pdfDocument builds a minimal but genuinely valid one-page PDF: catalog, page
// tree, page, Helvetica font and a content stream, followed by a cross-
// reference table whose offsets are computed from the bytes actually written.
// A viewer opens it; more importantly the file starts with "%PDF-", which is
// what the upload's content sniffing requires.
func pdfDocument(title, fileName string, version int) []byte {
	content := pdfContentStream(documentLines(title, fileName, version))

	objects := []string{
		"<< /Type /Catalog /Pages 2 0 R >>",
		"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] " +
			"/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
		"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
		"<< /Length " + strconv.Itoa(len(content)) + " >>\nstream\n" + content + "endstream",
	}

	var buf bytes.Buffer
	buf.WriteString("%PDF-1.4\n")
	offsets := make([]int, len(objects))
	for i, obj := range objects {
		offsets[i] = buf.Len()
		buf.WriteString(strconv.Itoa(i+1) + " 0 obj\n")
		buf.WriteString(obj)
		buf.WriteString("\nendobj\n")
	}

	xref := buf.Len()
	buf.WriteString("xref\n0 " + strconv.Itoa(len(objects)+1) + "\n")
	buf.WriteString("0000000000 65535 f \n")
	for _, offset := range offsets {
		buf.WriteString(fmt.Sprintf("%010d 00000 n \n", offset))
	}
	buf.WriteString("trailer\n<< /Size " + strconv.Itoa(len(objects)+1) + " /Root 1 0 R >>\n")
	buf.WriteString("startxref\n" + strconv.Itoa(xref) + "\n%%EOF\n")
	return buf.Bytes()
}

// pdfContentStream lays the lines out down the page in 14pt Helvetica.
func pdfContentStream(lines []string) string {
	var b strings.Builder
	b.WriteString("BT\n/F1 14 Tf\n16 TL\n60 780 Td\n")
	for _, line := range lines {
		b.WriteString("(" + pdfEscape(line) + ") Tj\nT*\n")
	}
	b.WriteString("ET\n")
	return b.String()
}

// pdfEscape escapes the three characters that are special inside a PDF literal
// string, and drops anything outside printable ASCII (the base Helvetica
// encoding has no glyph for it, and the demo labels are ASCII anyway).
func pdfEscape(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '\\' || r == '(' || r == ')':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r >= 0x20 && r < 0x7f:
			b.WriteRune(r)
		default:
			b.WriteByte('?')
		}
	}
	return b.String()
}
