// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewInternalAPIKeyRepoMock creates a new instance of InternalAPIKeyRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInternalAPIKeyRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *InternalAPIKeyRepoMock {
	mock := &InternalAPIKeyRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InternalAPIKeyRepoMock is an autogenerated mock type for the InternalAPIKeyRepo type
type InternalAPIKeyRepoMock struct {
	mock.Mock
}

type InternalAPIKeyRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *InternalAPIKeyRepoMock) EXPECT() *InternalAPIKeyRepoMock_Expecter {
	return &InternalAPIKeyRepoMock_Expecter{mock: &_m.Mock}
}

// GetByKey provides a mock function for the type InternalAPIKeyRepoMock
func (_mock *InternalAPIKeyRepoMock) GetByKey(ctx context.Context, key uuid.UUID) (*InternalAPIKey, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 *InternalAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*InternalAPIKey, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *InternalAPIKey); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*InternalAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InternalAPIKeyRepoMock_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type InternalAPIKeyRepoMock_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key uuid.UUID
func (_e *InternalAPIKeyRepoMock_Expecter) GetByKey(ctx interface{}, key interface{}) *InternalAPIKeyRepoMock_GetByKey_Call {
	return &InternalAPIKeyRepoMock_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, key)}
}

func (_c *InternalAPIKeyRepoMock_GetByKey_Call) Run(run func(ctx context.Context, key uuid.UUID)) *InternalAPIKeyRepoMock_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InternalAPIKeyRepoMock_GetByKey_Call) Return(internalAPIKey *InternalAPIKey, err error) *InternalAPIKeyRepoMock_GetByKey_Call {
	_c.Call.Return(internalAPIKey, err)
	return _c
}

func (_c *InternalAPIKeyRepoMock_GetByKey_Call) RunAndReturn(run func(ctx context.Context, key uuid.UUID) (*InternalAPIKey, error)) *InternalAPIKeyRepoMock_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewValidatorMock creates a new instance of ValidatorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidatorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidatorMock {
	mock := &ValidatorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ValidatorMock is an autogenerated mock type for the Validator type
type ValidatorMock struct {
	mock.Mock
}

type ValidatorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidatorMock) EXPECT() *ValidatorMock_Expecter {
	return &ValidatorMock_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type ValidatorMock
func (_mock *ValidatorMock) Validate(ctx context.Context, key string, secret string) (*AuthResult, error) {
	ret := _mock.Called(ctx, key, secret)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*AuthResult, error)); ok {
		return returnFunc(ctx, key, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *AuthResult); ok {
		r0 = returnFunc(ctx, key, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ValidatorMock_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ValidatorMock_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - secret string
func (_e *ValidatorMock_Expecter) Validate(ctx interface{}, key interface{}, secret interface{}) *ValidatorMock_Validate_Call {
	return &ValidatorMock_Validate_Call{Call: _e.mock.On("Validate", ctx, key, secret)}
}

func (_c *ValidatorMock_Validate_Call) Run(run func(ctx context.Context, key string, secret string)) *ValidatorMock_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ValidatorMock_Validate_Call) Return(authResult *AuthResult, err error) *ValidatorMock_Validate_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *ValidatorMock_Validate_Call) RunAndReturn(run func(ctx context.Context, key string, secret string) (*AuthResult, error)) *ValidatorMock_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewNexusAccountAPIKeyRepoMock creates a new instance of NexusAccountAPIKeyRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNexusAccountAPIKeyRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *NexusAccountAPIKeyRepoMock {
	mock := &NexusAccountAPIKeyRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NexusAccountAPIKeyRepoMock is an autogenerated mock type for the NexusAccountAPIKeyRepo type
type NexusAccountAPIKeyRepoMock struct {
	mock.Mock
}

type NexusAccountAPIKeyRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *NexusAccountAPIKeyRepoMock) EXPECT() *NexusAccountAPIKeyRepoMock_Expecter {
	return &NexusAccountAPIKeyRepoMock_Expecter{mock: &_m.Mock}
}

// GetByNexusAccountID provides a mock function for the type NexusAccountAPIKeyRepoMock
func (_mock *NexusAccountAPIKeyRepoMock) GetByNexusAccountID(ctx context.Context, nexusAccountID int) (*NexusAccountAPIKey, error) {
	ret := _mock.Called(ctx, nexusAccountID)

	if len(ret) == 0 {
		panic("no return value specified for GetByNexusAccountID")
	}

	var r0 *NexusAccountAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*NexusAccountAPIKey, error)); ok {
		return returnFunc(ctx, nexusAccountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *NexusAccountAPIKey); ok {
		r0 = returnFunc(ctx, nexusAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NexusAccountAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, nexusAccountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNexusAccountID'
type NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call struct {
	*mock.Call
}

// GetByNexusAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - nexusAccountID int
func (_e *NexusAccountAPIKeyRepoMock_Expecter) GetByNexusAccountID(ctx interface{}, nexusAccountID interface{}) *NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call {
	return &NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call{Call: _e.mock.On("GetByNexusAccountID", ctx, nexusAccountID)}
}

func (_c *NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call) Run(run func(ctx context.Context, nexusAccountID int)) *NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call) Return(nexusAccountAPIKey *NexusAccountAPIKey, err error) *NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call {
	_c.Call.Return(nexusAccountAPIKey, err)
	return _c
}

func (_c *NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call) RunAndReturn(run func(ctx context.Context, nexusAccountID int) (*NexusAccountAPIKey, error)) *NexusAccountAPIKeyRepoMock_GetByNexusAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type NexusAccountAPIKeyRepoMock
func (_mock *NexusAccountAPIKeyRepoMock) Store(ctx context.Context, input StoreNexusAPIKeyInput) (*NexusAccountAPIKey, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 *NexusAccountAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, StoreNexusAPIKeyInput) (*NexusAccountAPIKey, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, StoreNexusAPIKeyInput) *NexusAccountAPIKey); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NexusAccountAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, StoreNexusAPIKeyInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NexusAccountAPIKeyRepoMock_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type NexusAccountAPIKeyRepoMock_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - input StoreNexusAPIKeyInput
func (_e *NexusAccountAPIKeyRepoMock_Expecter) Store(ctx interface{}, input interface{}) *NexusAccountAPIKeyRepoMock_Store_Call {
	return &NexusAccountAPIKeyRepoMock_Store_Call{Call: _e.mock.On("Store", ctx, input)}
}

func (_c *NexusAccountAPIKeyRepoMock_Store_Call) Run(run func(ctx context.Context, input StoreNexusAPIKeyInput)) *NexusAccountAPIKeyRepoMock_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 StoreNexusAPIKeyInput
		if args[1] != nil {
			arg1 = args[1].(StoreNexusAPIKeyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NexusAccountAPIKeyRepoMock_Store_Call) Return(nexusAccountAPIKey *NexusAccountAPIKey, err error) *NexusAccountAPIKeyRepoMock_Store_Call {
	_c.Call.Return(nexusAccountAPIKey, err)
	return _c
}

func (_c *NexusAccountAPIKeyRepoMock_Store_Call) RunAndReturn(run func(ctx context.Context, input StoreNexusAPIKeyInput) (*NexusAccountAPIKey, error)) *NexusAccountAPIKeyRepoMock_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewNexusAccountAPIKeyUseCasesMock creates a new instance of NexusAccountAPIKeyUseCasesMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNexusAccountAPIKeyUseCasesMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *NexusAccountAPIKeyUseCasesMock {
	mock := &NexusAccountAPIKeyUseCasesMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NexusAccountAPIKeyUseCasesMock is an autogenerated mock type for the NexusAccountAPIKeyUseCases type
type NexusAccountAPIKeyUseCasesMock struct {
	mock.Mock
}

type NexusAccountAPIKeyUseCasesMock_Expecter struct {
	mock *mock.Mock
}

func (_m *NexusAccountAPIKeyUseCasesMock) EXPECT() *NexusAccountAPIKeyUseCasesMock_Expecter {
	return &NexusAccountAPIKeyUseCasesMock_Expecter{mock: &_m.Mock}
}

// GetByNexusAccountID provides a mock function for the type NexusAccountAPIKeyUseCasesMock
func (_mock *NexusAccountAPIKeyUseCasesMock) GetByNexusAccountID(ctx context.Context, nexusAccountID int) (*NexusAccountAPIKey, error) {
	ret := _mock.Called(ctx, nexusAccountID)

	if len(ret) == 0 {
		panic("no return value specified for GetByNexusAccountID")
	}

	var r0 *NexusAccountAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*NexusAccountAPIKey, error)); ok {
		return returnFunc(ctx, nexusAccountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *NexusAccountAPIKey); ok {
		r0 = returnFunc(ctx, nexusAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NexusAccountAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, nexusAccountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNexusAccountID'
type NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call struct {
	*mock.Call
}

// GetByNexusAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - nexusAccountID int
func (_e *NexusAccountAPIKeyUseCasesMock_Expecter) GetByNexusAccountID(ctx interface{}, nexusAccountID interface{}) *NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call {
	return &NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call{Call: _e.mock.On("GetByNexusAccountID", ctx, nexusAccountID)}
}

func (_c *NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call) Run(run func(ctx context.Context, nexusAccountID int)) *NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call) Return(nexusAccountAPIKey *NexusAccountAPIKey, err error) *NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call {
	_c.Call.Return(nexusAccountAPIKey, err)
	return _c
}

func (_c *NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call) RunAndReturn(run func(ctx context.Context, nexusAccountID int) (*NexusAccountAPIKey, error)) *NexusAccountAPIKeyUseCasesMock_GetByNexusAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// StoreExternalAPIKey provides a mock function for the type NexusAccountAPIKeyUseCasesMock
func (_mock *NexusAccountAPIKeyUseCasesMock) StoreExternalAPIKey(ctx context.Context, input StoreNexusAPIKeyInput) (*NexusAccountAPIKey, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for StoreExternalAPIKey")
	}

	var r0 *NexusAccountAPIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, StoreNexusAPIKeyInput) (*NexusAccountAPIKey, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, StoreNexusAPIKeyInput) *NexusAccountAPIKey); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NexusAccountAPIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, StoreNexusAPIKeyInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreExternalAPIKey'
type NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call struct {
	*mock.Call
}

// StoreExternalAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - input StoreNexusAPIKeyInput
func (_e *NexusAccountAPIKeyUseCasesMock_Expecter) StoreExternalAPIKey(ctx interface{}, input interface{}) *NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call {
	return &NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call{Call: _e.mock.On("StoreExternalAPIKey", ctx, input)}
}

func (_c *NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call) Run(run func(ctx context.Context, input StoreNexusAPIKeyInput)) *NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 StoreNexusAPIKeyInput
		if args[1] != nil {
			arg1 = args[1].(StoreNexusAPIKeyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call) Return(nexusAccountAPIKey *NexusAccountAPIKey, err error) *NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call {
	_c.Call.Return(nexusAccountAPIKey, err)
	return _c
}

func (_c *NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call) RunAndReturn(run func(ctx context.Context, input StoreNexusAPIKeyInput) (*NexusAccountAPIKey, error)) *NexusAccountAPIKeyUseCasesMock_StoreExternalAPIKey_Call {
	_c.Call.Return(run)
	return _c
}
