-- Deploy audit_log
BEGIN;

-- Application/business audit trail (ADR-0008, stream 1): PII-free envelope,
-- actor-by-ID, append-only, per-tenant hash chain.
--
-- Integrity model:
--   * Append-only at the DATABASE: RLS policies exist ONLY for INSERT and
--     SELECT — with FORCE RLS, UPDATE/DELETE match no policy and affect zero
--     rows even for the table owner. (Production provisioning additionally
--     grants the app role INSERT+SELECT only; TRUNCATE stays revoked.)
--   * Per-tenant hash chain: hash = sha256(prev_hash || canonical envelope);
--     seq is per-tenant monotonic. Appends within a tenant are serialized by a
--     per-tenant advisory xact lock in the writer (parallel across tenants).
--     Any edit/deletion/reorder breaks recomputation → tamper-evident.
--   * WORM export to S3 Object Lock is Phase 2 (per the ADR).
--
-- PII rule: details carries ONLY explicitly whitelisted non-PII values (enum
-- transitions, counts, ids). Names are resolved at read time from the user row.
--
-- Partitioned by RANGE(occurred_at), monthly (ADR-0020): the fastest-growing
-- append-only stream. Retention (ADR-0007) and WORM export (ADR-0008) become
-- per-partition lifecycle: export, then DETACH/DROP. Conscious trade-off: the
-- unique on (tenant_id, seq) must include the partition key, so it is
-- effectively per-partition — sequence integrity is guaranteed by the
-- advisory-lock-serialized writer and VERIFIED by the hash chain (duplicates,
-- gaps, and reorders all break recomputation); the chain, not the index, is
-- the ledger's integrity mechanism.
CREATE TABLE audit_log (
    event_id      UUID NOT NULL,
    tenant_id     UUID NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::uuid
        REFERENCES tenants(id) ON DELETE RESTRICT,
    seq           BIGINT NOT NULL,
    actor_id      UUID NOT NULL,          -- user id; NEVER a name (ADR-0007/0008)
    action        VARCHAR(60) NOT NULL,   -- e.g. entity.created, task_instance.approved
    resource_type VARCHAR(40) NOT NULL,
    resource_id   UUID NOT NULL,
    occurred_at   TIMESTAMPTZ NOT NULL,   -- generated by the writer (hashed value = stored value)
    request_id    TEXT NOT NULL DEFAULT '',
    details       JSONB NOT NULL DEFAULT '{}'::jsonb,
    prev_hash     CHAR(64) NOT NULL,      -- sha256 hex of the previous entry; 64 zeros at genesis
    hash          CHAR(64) NOT NULL,
    PRIMARY KEY (event_id, occurred_at),
    UNIQUE (tenant_id, seq, occurred_at)
) PARTITION BY RANGE (occurred_at);

SELECT ensure_month_partitions('audit_log', DATE '2026-08-01', 3);
CREATE TABLE audit_log_default PARTITION OF audit_log DEFAULT;
ALTER TABLE audit_log_default ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log_default FORCE ROW LEVEL SECURITY;

CREATE INDEX idx_audit_log_tenant_seq ON audit_log (tenant_id, seq DESC);
CREATE INDEX idx_audit_log_resource ON audit_log (resource_type, resource_id);

ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log FORCE ROW LEVEL SECURITY;

-- Deliberately NO policy FOR UPDATE or FOR DELETE: append-only.
CREATE POLICY tenant_read ON audit_log FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY tenant_append ON audit_log FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

COMMIT;
